In [1]:
print("hello")

hello


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
a.ndim


1

In [7]:
array([[1,2,3,4,5]])
a

NameError: name 'array' is not defined

In [8]:
a=np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [9]:
a.ndim


2

In [10]:
b=np.array([4,5,6,7,8])
b

array([4, 5, 6, 7, 8])

In [11]:
a
b

array([4, 5, 6, 7, 8])

In [12]:
a+b

ValueError: operands could not be broadcast together with shapes (1,3) (5,) 

In [13]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [14]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
a.ndim

2

In [16]:
a[1,:]

array([5, 6, 7, 8])

In [17]:
a[:1]

array([[1, 2, 3, 4]])

In [18]:
a[:1,:2]

array([[1, 2]])

In [19]:
a[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [20]:
a[:2,3:]

array([[4],
       [8]])

In [21]:
a[:,1:2]

array([[ 2],
       [ 6],
       [10]])

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

In [24]:
a.shape

(3, 4)

In [25]:
a=np.random.rand(4)

In [26]:
a

array([0.46129713, 0.37528878, 0.06013814, 0.21185074])

In [27]:
a.dtype

dtype('float64')

In [28]:
np.head()

AttributeError: module 'numpy' has no attribute 'head'

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.twos((3,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [31]:
np.two((2,2)

SyntaxError: unexpected EOF while parsing (<ipython-input-31-53c4d7735cb5>, line 1)

In [32]:
x=np.ones((3,4))

In [33]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.sin(a)

array([0.44511003, 0.36654123, 0.0601019 , 0.21026962])

In [36]:
np.cos(a)

array([0.89547588, 0.93040181, 0.99819225, 0.97764344])

In [37]:
np.tan(a)

array([0.49706535, 0.39396014, 0.06021075, 0.21507803])

In [1]:
b

NameError: name 'b' is not defined

In [2]:
a=np.array([8,6,4,9])
b=np.array([5,0,3,2])

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
a=np.array([8,6,4,9])
b=np.array([5,0,3,2])

In [5]:
a+2

array([10,  8,  6, 11])

In [6]:
b+7

array([12,  7, 10,  9])

In [7]:
a+b

array([13,  6,  7, 11])

In [8]:
a-b

array([3, 6, 1, 7])

In [9]:
a*b

array([40,  0, 12, 18])

In [10]:
a/b

<ipython-input-10-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([1.6       ,        inf, 1.33333333, 4.5       ])

In [11]:
a\b

SyntaxError: unexpected character after line continuation character (<ipython-input-11-258d3300fba0>, line 1)

In [12]:
a-b

array([3, 6, 1, 7])

In [13]:
a-6

array([ 2,  0, -2,  3])

In [14]:
a*8

array([64, 48, 32, 72])

In [15]:
b/2

array([2.5, 0. , 1.5, 1. ])

In [16]:
np.matmul(a,b)

70

In [17]:
np.empty

<function numpy.empty>

In [18]:
np.arrange(10,30,5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [19]:
a

array([8, 6, 4, 9])

In [20]:
np.linspace(8,6,4,9)

array([8.        , 7.33333333, 6.66666667, 6.        ])

In [21]:
np.exp(a)

array([2980.95798704,  403.42879349,   54.59815003, 8103.08392758])

In [22]:
np.sqrt(b)

array([2.23606798, 0.        , 1.73205081, 1.41421356])

In [23]:
np.sqrt(a)

array([2.82842712, 2.44948974, 2.        , 3.        ])

In [24]:
np.add(a,b)

array([13,  6,  7, 11])

In [25]:
a.ravel()

array([8, 6, 4, 9])